[build.environment]
  NODE_VERSION = "22.17.1"

[build]
  command = "npm install --legacy-peer-deps && ng build --configuration production"
  publish = "dist/frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
